### PR TITLE
Add travis for container image build

### PR DESCRIPTION
**Pull request by bdunne**
Important: This changes from using `latest` tag to `1` since `memcached-1.5.22-2.el8.x86_64` is installed.

### CODE REVIEW

**Comment by Fryguy** [comment]
`1` feels strange...does `1.5` make more sense?  Do we even know what version we are going to get?

**Comment by chessbyte** [comment]
or even `1.5.x`?

**Comment by bdunne** [comment]
> Do we even know what version we are going to get?

Only if we give the full version number `memcached-1.5.22`, but I'd rather not be so specific.

**Comment by Fryguy** [comment]
@bdunne Try `--entrypoint /bin/bash` and then only the `-c...` at the end

**Comment by bdunne** [comment]
I added some logic to extract the rpm version from the built image and will push both `docker.io/manageiq/memcached:1` and `docker.io/manageiq/memcached:1.5` in this case.

**Pull request merged**
